const fs = require('fs');

function updateDict(file, updates) {
  const data = JSON.parse(fs.readFileSync(file));
  data.legal = data.legal || {};
  
  data.legal.privacy = updates.privacy;
  data.legal.cookies = updates.cookies;
  data.legal.terms = updates.terms;
  
  fs.writeFileSync(file, JSON.stringify(data, null, 2));
}

const esUpdates = {
  privacy: {
    title: "Política de Privacidad",
    lastUpdated: "Última actualización: marzo de 2026",
    intro: "En Cambiocromos.com, nos tomamos muy en serio tu privacidad. Esta política describe cómo recopilamos, utilizamos y protegemos tu información personal, en cumplimiento con el Reglamento General de Protección de Datos (RGPD) y la LOPDGDD.",
    section1Title: "1. Responsable del Tratamiento",
    section1Desc: "El responsable del tratamiento de los datos es el equipo de administración de Cambiocromos.com. Para cualquier cuestión relativa a la privacidad, puedes contactar con nuestro Delegado de Protección de Datos en:",
    section2Title: "2. Qué datos recopilamos",
    section2Li1: "<strong>Datos de Identificación:</strong> Correo electrónico, nombre de usuario (nickname), imagen de perfil (avatar).",
    section2Li2: "<strong>Datos de Localización:</strong> Código postal (para facilitar intercambios cercanos), país y provincia.",
    section2Li3: "<strong>Datos de Uso:</strong> Información sobre tus colecciones, listas de faltas/repes, interacciones y chats.",
    section2Li4: "<strong>Datos Técnicos:</strong> Dirección IP, tipo de dispositivo y navegador (con fines de seguridad y analítica).",
    section3Title: "3. Finalidad del tratamiento",
    section3Intro: "Utilizamos tus datos para:",
    section3Li1: "Gestionar tu cuenta de usuario y permitir el acceso a la plataforma.",
    section3Li2: "Facilitar el sistema de emparejamiento (matching) para encontrar otros coleccionistas cercanos.",
    section3Li3: "Permitir la comunicación entre usuarios a través del chat interno.",
    section3Li4: "Enviar notificaciones importantes sobre el servicio (puedes desactivarlas).",
    section3Li5: "Garantizar la seguridad de la plataforma y prevenir fraudes.",
    section4Title: "4. Legitimación",
    section4Desc: "La base legal para el tratamiento de tus datos es la <strong>ejecución del contrato</strong> (Términos de Servicio) al que te suscribes al registrarte, así como tu <strong>consentimiento expreso</strong> para ciertas funcionalidades (como la ubicación aproximada).",
    section5Title: "5. Destinatarios y Terceros",
    section5Intro: "No vendemos tus datos a terceros. Compartimos información solo con proveedores de servicios estrictamente necesarios para el funcionamiento de la app:",
    section5Li1: "<strong>Supabase:</strong> Proveedor de base de datos y autenticación.",
    section5Li2: "<strong>Google Analytics:</strong> Para análisis anónimo de tráfico web.",
    section5Li3: "<strong>OneSignal:</strong> Para el envío de notificaciones push.",
    section6Title: "6. Conservación de Datos",
    section6Intro: "Mantendremos tus datos mientras tu cuenta permanezca activa. Si decides eliminar tu cuenta:",
    section6Li1: "Tus datos personales directos (email, perfil) serán eliminados o anonimizados de inmediato o tras un periodo de gracia de 30 días para evitar eliminaciones accidentales.",
    section6Li2: "Las copias de seguridad de la base de datos se eliminan automáticamente según nuestro ciclo de retención (máximo 90 días).",
    section7Title: "7. Tus Derechos",
    section7Intro: "Como usuario, tienes derecho a:",
    section7Li1: "<strong>Acceder</strong> a tus datos y saber qué información tenemos.",
    section7Li2: "<strong>Rectificar</strong> datos incorrectos o incompletos desde tu perfil.",
    section7Li3: "<strong>Suprimir</strong> tus datos (\"Derecho al olvido\") mediante la opción \"Borrar Cuenta\" en los Ajustes.",
    section7Li4: "<strong>Limitar</strong> el tratamiento de tus datos en ciertas circunstancias.",
    section7Li5: "<strong>Portabilidad:</strong> Solicitar una copia de tus datos en un formato estructurado.",
    section7Outro: "Puedes ejercer estos derechos escribiendo a"
  },
  cookies: {
    title: "Política de Cookies",
    intro: "Cambiocromos.com utiliza cookies y tecnologías similares para mejorar tu experiencia, garantizar la seguridad del sitio y analizar cómo se utiliza nuestra plataforma.",
    section1Title: "1. ¿Qué son las cookies?",
    section1Desc: "Las cookies son pequeños archivos de texto que los sitios web guardan en tu ordenador o dispositivo móvil cuando los visitas. Permiten que el sitio recuerde tus acciones y preferencias (como el inicio de sesión) durante un período de tiempo.",
    section2Title: "2. Tipos de cookies que utilizamos",
    section2Sub1: "Cookies Esenciales (Técnicas)",
    section2Sub1Intro: "Son estrictamente necesarias para el funcionamiento del sitio web. Nos permiten:",
    section2Sub1Li1: "Mantener tu sesión iniciada de forma segura (Autenticación con Supabase).",
    section2Sub1Li2: "Recordar tus preferencias de privacidad.",
    section2Sub1Li3: "Proteger la web contra ataques automatizados.",
    section2Sub2: "Cookies de Análisis",
    section2Sub2Intro: "Utilizamos Google Analytics para recopilar información anónima sobre cómo los visitantes usan nuestro sitio. Esto nos ayuda a mejorar el rendimiento y la usabilidad.",
    section2Sub2Li1: "Estas cookies no recopilan información que te identifique personalmente.",
    section2Sub2Li2: "Toda la información es agregada y, por lo tanto, anónima.",
    section3Title: "3. Cómo controlar las cookies",
    section3Desc: "Puedes controlar y/o eliminar las cookies como desees. Puedes eliminar todas las cookies que ya están en tu ordenador y puedes configurar la mayoría de los navegadores para que eviten que se coloquen. Sin embargo, si haces esto, es posible que tengas que ajustar manualmente algunas preferencias cada vez que visites un sitio y que algunos servicios y funcionalidades (como el inicio de sesión) no funcionen."
  },
  terms: {
    title: "Términos de Servicio",
    lastUpdated: "Última actualización: marzo de 2026",
    section1Title: "1. Aceptación de los Términos",
    section1Desc: "Bienvenido a Cambiocromos.com. Al acceder, registrarse o utilizar nuestra plataforma, usted (\"Usuario\") acepta estar legalmente vinculado por estos Términos de Servicio (\"Términos\"). Si no está de acuerdo con alguna parte de estos términos, no debe utilizar nuestros servicios.",
    alertTitle: "Servicio exclusivo para mayores de 18 años",
    alertDesc: "Debido a la naturaleza social de la plataforma (interacción con desconocidos, chats privados y transacciones), <strong>Cambiocromos.com está reservado exclusivamente para personas mayores de 18 años</strong>. Al registrarse, usted declara y garantiza que tiene al menos 18 años de edad. Las cuentas que se detecten pertenecientes a menores de edad serán suspendidas inmediatamente y sin previo aviso.",
    section2Title: "2. Cuentas de Usuario",
    section2Desc: "Para utilizar ciertas funciones, debe registrarse y crear una cuenta. Usted es responsable de mantener la confidencialidad de su contraseña y de todas las actividades que ocurran bajo su cuenta. Nos reservamos el derecho de suspender o eliminar cuentas que incumplan estos términos, proporcionen información falsa o permanezcan inactivas por periodos prolongados.",
    section3Title: "3. Contenido Generado por el Usuario (UGC)",
    section3Intro: "Nuestra plataforma permite a los usuarios publicar imágenes (cromos), crear colecciones y enviar mensajes. Respecto a este contenido:",
    section3Li1: "<strong>Propiedad:</strong> Usted conserva los derechos de propiedad intelectual sobre el contenido que crea y sube. Sin embargo, al publicarlo, otorga a Cambiocromos.com una licencia mundial, no exclusiva y gratuita para usar, mostrar y distribuir dicho contenido en relación con el servicio.",
    section3Li2: "<strong>Responsabilidad del Usuario:</strong> Usted es el <strong>único responsable</strong> de todo el contenido que publique. Declara que posee todos los derechos necesarios o autorizaciones para publicar dicho contenido y que este no infringe derechos de terceros.",
    section3Li3: "<strong>Moderación:</strong> Cambiocromos.com no tiene la obligación de previsualizar el contenido, pero tiene el <strong>derecho absoluto y a su entera discreción de revisar, rechazar o eliminar cualquier contenido</strong> que considere inapropiado, ilegal o que viole estos Términos, sin previo aviso.",
    section31Title: "3.1. Contenido Prohibido",
    section31Intro: "Queda terminantemente prohibido publicar:",
    section31Li1: "Contenido ilegal, difamatorio, obsceno, pornográfico, indecente o amenazante.",
    section31Li2: "Discurso de odio, acoso o discriminación hacia otros usuarios.",
    section31Li3: "Material que infrinja derechos de autor, marcas registradas o propiedad intelectual de terceros.",
    section31Li4: "Spam, publicidad no autorizada o enlaces a sitios maliciosos.",
    section4Title: "4. Interacciones Sociales y Seguridad",
    section4Intro: "Cambiocromos.com facilita el contacto entre usuarios. Usted reconoce que:",
    section4Li1: "Está interactuando con personas que pueden ser desconocidas para usted.",
    section4Li2: "Es responsable de ejercer precaución en todas las interacciones, especialmente al compartir información o acordar envíos.",
    section4Li3: "<strong>Tolerancia Cero:</strong> No toleramos el acoso, los insultos ni el comportamiento abusivo. Disponemos de herramientas para <strong>Reportar</strong> y <strong>Bloquear</strong> usuarios. Cualquier reporte verificado de abuso resultará en la suspensión inmediata de la cuenta infractora.",
    section5Title: "5. Exención de Responsabilidad",
    section5Desc: "Cambiocromos.com actúa únicamente como intermediario tecnológico. No somos parte en ninguna transacción de intercambio o venta entre usuarios. No garantizamos la veracidad de los anuncios, la calidad de los cromos ni el cumplimiento de los acuerdos entre usuarios. Usted libera a Cambiocromos.com de cualquier reclamación, demanda o daño relacionado con disputas con otros usuarios.",
    section6Title: "6. Modificaciones",
    section6Desc: "Nos reservamos el derecho de modificar estos términos en cualquier momento. Las modificaciones entrarán en vigor inmediatamente después de su publicación. El uso continuado del servicio implica la aceptación de los nuevos términos.",
    section7Title: "7. Contacto",
    section7Desc: "Para reportar infracciones o consultas legales, contáctenos en:"
  }
};

const enUpdates = {
  privacy: {
    title: "Privacy Policy",
    lastUpdated: "Last updated: March 2026",
    intro: "At Cambiocromos.com, we take your privacy very seriously. This policy describes how we collect, use, and protect your personal information, in compliance with the General Data Protection Regulation (GDPR) and LOPDGDD.",
    section1Title: "1. Data Controller",
    section1Desc: "The data controller is the Cambiocromos.com administration team. For any privacy-related issues, you can contact our Data Protection Officer at:",
    section2Title: "2. What data we collect",
    section2Li1: "<strong>Identification Data:</strong> Email, username (nickname), profile picture (avatar).",
    section2Li2: "<strong>Location Data:</strong> Postal code (to facilitate nearby trades), country, and province.",
    section2Li3: "<strong>Usage Data:</strong> Information about your collections, missing/duplicate lists, interactions, and chats.",
    section2Li4: "<strong>Technical Data:</strong> IP address, device type, and browser (for security and analytics purposes).",
    section3Title: "3. Purpose of processing",
    section3Intro: "We use your data to:",
    section3Li1: "Manage your user account and allow access to the platform.",
    section3Li2: "Facilitate the matching system to find other nearby collectors.",
    section3Li3: "Allow communication between users through the internal chat.",
    section3Li4: "Send important notifications about the service (you can disable them).",
    section3Li5: "Ensure the security of the platform and prevent fraud.",
    section4Title: "4. Legitimation",
    section4Desc: "The legal basis for processing your data is the <strong>performance of the contract</strong> (Terms of Service) you agree to when registering, as well as your <strong>explicit consent</strong> for certain features (such as approximate location).",
    section5Title: "5. Recipients and Third Parties",
    section5Intro: "We do not sell your data to third parties. We share information only with service providers strictly necessary for the operation of the app:",
    section5Li1: "<strong>Supabase:</strong> Database and authentication provider.",
    section5Li2: "<strong>Google Analytics:</strong> For anonymous web traffic analysis.",
    section5Li3: "<strong>OneSignal:</strong> For sending push notifications.",
    section6Title: "6. Data Retention",
    section6Intro: "We will keep your data as long as your account remains active. If you decide to delete your account:",
    section6Li1: "Your direct personal data (email, profile) will be deleted or anonymized immediately or after a 30-day grace period to prevent accidental deletions.",
    section6Li2: "Database backups are automatically deleted according to our retention cycle (maximum 90 days).",
    section7Title: "7. Your Rights",
    section7Intro: "As a user, you have the right to:",
    section7Li1: "<strong>Access</strong> your data and know what information we hold.",
    section7Li2: "<strong>Rectify</strong> incorrect or incomplete data from your profile.",
    section7Li3: "<strong>Erase</strong> your data (\"Right to be forgotten\") through the \"Delete Account\" option in Settings.",
    section7Li4: "<strong>Restrict</strong> the processing of your data in certain circumstances.",
    section7Li5: "<strong>Portability:</strong> Request a copy of your data in a structured format.",
    section7Outro: "You can exercise these rights by writing to"
  },
  cookies: {
    title: "Cookie Policy",
    intro: "Cambiocromos.com uses cookies and similar technologies to improve your experience, ensure site security, and analyze how our platform is used.",
    section1Title: "1. What are cookies?",
    section1Desc: "Cookies are small text files that websites save on your computer or mobile device when you visit them. They allow the site to remember your actions and preferences (such as login) over a period of time.",
    section2Title: "2. Types of cookies we use",
    section2Sub1: "Essential Cookies (Technical)",
    section2Sub1Intro: "They are strictly necessary for the operation of the website. They allow us to:",
    section2Sub1Li1: "Keep your session securely logged in (Authentication with Supabase).",
    section2Sub1Li2: "Remember your privacy preferences.",
    section2Sub1Li3: "Protect the web against automated attacks.",
    section2Sub2: "Analytics Cookies",
    section2Sub2Intro: "We use Google Analytics to collect anonymous information about how visitors use our site. This helps us improve performance and usability.",
    section2Sub2Li1: "These cookies do not collect information that personally identifies you.",
    section2Sub2Li2: "All information is aggregated and therefore anonymous.",
    section3Title: "3. How to control cookies",
    section3Desc: "You can control and/or delete cookies as you wish. You can delete all cookies that are already on your computer and you can set most browsers to prevent them from being placed. However, if you do this, you may have to manually adjust some preferences every time you visit a site and some services and functionalities (such as logging in) may not work."
  },
  terms: {
    title: "Terms of Service",
    lastUpdated: "Last updated: March 2026",
    section1Title: "1. Acceptance of Terms",
    section1Desc: "Welcome to Cambiocromos.com. By accessing, registering or using our platform, you (\"User\") agree to be legally bound by these Terms of Service (\"Terms\"). If you do not agree with any part of these terms, you must not use our services.",
    alertTitle: "Service exclusively for adults over 18",
    alertDesc: "Due to the social nature of the platform (interaction with strangers, private chats, and transactions), <strong>Cambiocromos.com is reserved exclusively for people over 18 years of age</strong>. By registering, you represent and warrant that you are at least 18 years of age. Accounts found to belong to minors will be suspended immediately and without notice.",
    section2Title: "2. User Accounts",
    section2Desc: "To use certain features, you must register and create an account. You are responsible for maintaining the confidentiality of your password and all activities that occur under your account. We reserve the right to suspend or delete accounts that violate these terms, provide false information, or remain inactive for extended periods.",
    section3Title: "3. User Generated Content (UGC)",
    section3Intro: "Our platform allows users to publish images (stickers), create collections, and send messages. Regarding this content:",
    section3Li1: "<strong>Ownership:</strong> You retain intellectual property rights to the content you create and upload. However, by publishing it, you grant Cambiocromos.com a worldwide, non-exclusive, and free license to use, display, and distribute such content in connection with the service.",
    section3Li2: "<strong>User Responsibility:</strong> You are <strong>solely responsible</strong> for all content you publish. You declare that you have all necessary rights or authorizations to publish such content and that it does not infringe third-party rights.",
    section3Li3: "<strong>Moderation:</strong> Cambiocromos.com has no obligation to preview content, but has the <strong>absolute right and at its sole discretion to review, reject or delete any content</strong> it deems inappropriate, illegal or violating these Terms, without notice.",
    section31Title: "3.1. Prohibited Content",
    section31Intro: "It is strictly forbidden to publish:",
    section31Li1: "Illegal, defamatory, obscene, pornographic, indecent, or threatening content.",
    section31Li2: "Hate speech, harassment, or discrimination against other users.",
    section31Li3: "Material that infringes copyrights, trademarks, or third-party intellectual property.",
    section31Li4: "Spam, unauthorized advertising, or links to malicious sites.",
    section4Title: "4. Social Interactions and Security",
    section4Intro: "Cambiocromos.com facilitates contact between users. You acknowledge that:",
    section4Li1: "You are interacting with people who may be strangers to you.",
    section4Li2: "You are responsible for exercising caution in all interactions, especially when sharing information or arranging shipments.",
    section4Li3: "<strong>Zero Tolerance:</strong> We do not tolerate harassment, insults, or abusive behavior. We have tools to <strong>Report</strong> and <strong>Block</strong> users. Any verified report of abuse will result in immediate suspension of the offending account.",
    section5Title: "5. Disclaimer",
    section5Desc: "Cambiocromos.com acts solely as a technological intermediary. We are not a party to any exchange or sale transaction between users. We do not guarantee the veracity of the listings, the quality of the stickers, or the fulfillment of agreements between users. You release Cambiocromos.com from any claim, demand, or damage related to disputes with other users.",
    section6Title: "6. Modifications",
    section6Desc: "We reserve the right to modify these terms at any time. Modifications will take effect immediately upon publication. Continued use of the service implies acceptance of the new terms.",
    section7Title: "7. Contact",
    section7Desc: "To report violations or legal inquiries, contact us at:"
  }
};

const ptUpdates = {
  privacy: {
    title: "Política de Privacidade",
    lastUpdated: "Última atualização: março de 2026",
    intro: "No Cambiocromos.com, levamos a sua privacidade muito a sério. Esta política descreve como coletamos, usamos e protegemos suas informações pessoais, em conformidade com o Regulamento Geral de Proteção de Dados (RGPD) e a LOPDGDD.",
    section1Title: "1. Responsável pelo Tratamento",
    section1Desc: "O responsável pelo tratamento de dados é a equipe de administração do Cambiocromos.com. Para qualquer questão relacionada à privacidade, você pode entrar em contato com nosso Encarregado de Proteção de Dados em:",
    section2Title: "2. Que dados coletamos",
    section2Li1: "<strong>Dados de Identificação:</strong> E-mail, nome de usuário (nickname), foto de perfil (avatar).",
    section2Li2: "<strong>Dados de Localização:</strong> Código postal (para facilitar trocas próximas), país e província.",
    section2Li3: "<strong>Dados de Uso:</strong> Informações sobre suas coleções, listas de faltantes/repetidas, interações e chats.",
    section2Li4: "<strong>Dados Técnicos:</strong> Endereço IP, tipo de dispositivo e navegador (para fins de segurança e análise).",
    section3Title: "3. Finalidade do tratamento",
    section3Intro: "Usamos seus dados para:",
    section3Li1: "Gerenciar sua conta de usuário e permitir o acesso à plataforma.",
    section3Li2: "Facilitar o sistema de correspondência (matching) para encontrar outros colecionadores próximos.",
    section3Li3: "Permitir a comunicação entre os usuários por meio do chat interno.",
    section3Li4: "Enviar notificações importantes sobre o serviço (você pode desativá-las).",
    section3Li5: "Garantir a segurança da plataforma e prevenir fraudes.",
    section4Title: "4. Legitimação",
    section4Desc: "A base legal para o tratamento de seus dados é a <strong>execução do contrato</strong> (Termos de Serviço) com o qual você concorda ao se registrar, bem como seu <strong>consentimento expresso</strong> para determinados recursos (como localização aproximada).",
    section5Title: "5. Destinatários e Terceiros",
    section5Intro: "Não vendemos seus dados a terceiros. Compartilhamos informações apenas com provedores de serviços estritamente necessários para o funcionamento do aplicativo:",
    section5Li1: "<strong>Supabase:</strong> Provedor de banco de dados e autenticação.",
    section5Li2: "<strong>Google Analytics:</strong> Para análise anônima de tráfego na web.",
    section5Li3: "<strong>OneSignal:</strong> Para enviar notificações push.",
    section6Title: "6. Retenção de Dados",
    section6Intro: "Manteremos seus dados enquanto sua conta permanecer ativa. Se você decidir excluir sua conta:",
    section6Li1: "Seus dados pessoais diretos (e-mail, perfil) serão excluídos ou anonimizados imediatamente ou após um período de tolerância de 30 dias para evitar exclusões acidentais.",
    section6Li2: "Os backups do banco de dados são excluídos automaticamente de acordo com nosso ciclo de retenção (máximo de 90 dias).",
    section7Title: "7. Seus Direitos",
    section7Intro: "Como usuário, você tem o direito de:",
    section7Li1: "<strong>Acessar</strong> seus dados e saber quais informações mantemos.",
    section7Li2: "<strong>Retificar</strong> dados incorretos ou incompletos de seu perfil.",
    section7Li3: "<strong>Apagar</strong> seus dados (\"Direito de ser esquecido\") através da opção \"Excluir Conta\" nas Configurações.",
    section7Li4: "<strong>Limitar</strong> o processamento de seus dados em certas circunstâncias.",
    section7Li5: "<strong>Portabilidade:</strong> Solicitar uma cópia de seus dados em um formato estruturado.",
    section7Outro: "Você pode exercer esses direitos escrevendo para"
  },
  cookies: {
    title: "Política de Cookies",
    intro: "Cambiocromos.com usa cookies e tecnologias semelhantes para melhorar sua experiência, garantir a segurança do site e analisar como nossa plataforma é usada.",
    section1Title: "1. O que são cookies?",
    section1Desc: "Cookies são pequenos arquivos de texto que os sites salvam em seu computador ou dispositivo móvel quando você os visita. Eles permitem que o site se lembre de suas ações e preferências (como login) durante um período de tempo.",
    section2Title: "2. Tipos de cookies que usamos",
    section2Sub1: "Cookies Essenciais (Técnicos)",
    section2Sub1Intro: "Eles são estritamente necessários para o funcionamento do site. Eles nos permitem:",
    section2Sub1Li1: "Manter sua sessão conectada com segurança (Autenticação com Supabase).",
    section2Sub1Li2: "Lembrar de suas preferências de privacidade.",
    section2Sub1Li3: "Proteger a web contra ataques automatizados.",
    section2Sub2: "Cookies de Análise",
    section2Sub2Intro: "Usamos o Google Analytics para coletar informações anônimas sobre como os visitantes usam nosso site. Isso nos ajuda a melhorar o desempenho e a usabilidade.",
    section2Sub2Li1: "Estes cookies não coletam informações que o identifiquem pessoalmente.",
    section2Sub2Li2: "Toda a informação é agregada e, portanto, anônima.",
    section3Title: "3. Como controlar cookies",
    section3Desc: "Você pode controlar e/ou excluir cookies conforme desejar. Você pode excluir todos os cookies que já estão em seu computador e pode configurar a maioria dos navegadores para evitar que sejam colocados. No entanto, se fizer isso, você pode ter que ajustar manualmente algumas preferências cada vez que visitar um site e alguns serviços e funcionalidades (como fazer login) podem não funcionar."
  },
  terms: {
    title: "Termos de Serviço",
    lastUpdated: "Última atualização: março de 2026",
    section1Title: "1. Aceitação dos Termos",
    section1Desc: "Bem-vindo ao Cambiocromos.com. Ao acessar, registrar-se ou usar nossa plataforma, você (\"Usuário\") concorda em ficar legalmente vinculado a estes Termos de Serviço (\"Termos\"). Se você não concordar com qualquer parte destes termos, não deve usar nossos serviços.",
    alertTitle: "Serviço exclusivo para maiores de 18 anos",
    alertDesc: "Devido à natureza social da plataforma (interação com estranhos, chats privados e transações), <strong>Cambiocromos.com é reservado exclusivamente para pessoas maiores de 18 anos</strong>. Ao registrar-se, você declara e garante que tem pelo menos 18 anos de idade. Contas identificadas como pertencentes a menores serão suspensas imediatamente e sem aviso prévio.",
    section2Title: "2. Contas de Usuário",
    section2Desc: "Para usar determinados recursos, você deve se registrar e criar uma conta. Você é responsável por manter a confidencialidade de sua senha e por todas as atividades que ocorram sob sua conta. Nós nos reservamos o direito de suspender ou excluir contas que violem estes termos, forneçam informações falsas ou permaneçam inativas por longos períodos.",
    section3Title: "3. Conteúdo Gerado pelo Usuário (UGC)",
    section3Intro: "Nossa plataforma permite que os usuários publiquem imagens (figurinhas), criem coleções e enviem mensagens. Em relação a este conteúdo:",
    section3Li1: "<strong>Propriedade:</strong> Você retém os direitos de propriedade intelectual sobre o conteúdo que cria e envia. No entanto, ao publicá-lo, você concede à Cambiocromos.com uma licença mundial, não exclusiva e gratuita para usar, exibir e distribuir tal conteúdo em conexão com o serviço.",
    section3Li2: "<strong>Responsabilidade do Usuário:</strong> Você é o <strong>único responsável</strong> por todo o conteúdo que publica. Você declara que possui todos os direitos necessários ou autorizações para publicar esse conteúdo e que ele não infringe direitos de terceiros.",
    section3Li3: "<strong>Moderação:</strong> Cambiocromos.com não tem a obrigação de pré-visualizar o conteúdo, mas tem o <strong>direito absoluto e a seu exclusivo critério de revisar, rejeitar ou excluir qualquer conteúdo</strong> que considere inadequado, ilegal ou que viole estes Termos, sem aviso prévio.",
    section31Title: "3.1. Conteúdo Proibido",
    section31Intro: "É terminantemente proibido publicar:",
    section31Li1: "Conteúdo ilegal, difamatório, obsceno, pornográfico, indecente ou ameaçador.",
    section31Li2: "Discurso de ódio, assédio ou discriminação contra outros usuários.",
    section31Li3: "Material que infrinja direitos autorais, marcas registradas ou propriedade intelectual de terceiros.",
    section31Li4: "Spam, publicidade não autorizada ou links para sites maliciosos.",
    section4Title: "4. Interações Sociais e Segurança",
    section4Intro: "Cambiocromos.com facilita o contato entre os usuários. Você reconhece que:",
    section4Li1: "Você está interagindo com pessoas que podem ser estranhas para você.",
    section4Li2: "Você é responsável por ter cautela em todas as interações, especialmente ao compartilhar informações ou organizar envios.",
    section4Li3: "<strong>Tolerância Zero:</strong> Não toleramos assédio, insultos ou comportamento abusivo. Temos ferramentas para <strong>Denunciar</strong> e <strong>Bloquear</strong> usuários. Qualquer relato verificado de abuso resultará na suspensão imediata da conta infratora.",
    section5Title: "5. Isenção de Responsabilidade",
    section5Desc: "Cambiocromos.com atua apenas como um intermediário tecnológico. Não somos parte em nenhuma transação de troca ou venda entre usuários. Não garantimos a veracidade dos anúncios, a qualidade das figurinhas ou o cumprimento de acordos entre usuários. Você isenta Cambiocromos.com de qualquer reclamação, exigência ou dano relacionado a disputas com outros usuários.",
    section6Title: "6. Modificações",
    section6Desc: "Nós nos reservamos o direito de modificar estes termos a qualquer momento. As modificações entrarão em vigor imediatamente após a publicação. O uso continuado do serviço implica a aceitação dos novos termos.",
    section7Title: "7. Contato",
    section7Desc: "Para denunciar violações ou consultas legais, contate-nos em:"
  }
};

updateDict('src/i18n/messages/es.json', esUpdates);
updateDict('src/i18n/messages/en.json', enUpdates);
updateDict('src/i18n/messages/pt.json', ptUpdates);
console.log('Legal dictionaries updated!');
