-- =====================================================
-- BLOCK SUSPENDED USERS FROM LOGGING IN
-- =====================================================
-- Purpose: Prevent suspended users from authenticating
--
-- NOTE: This migration file documents the approach but the actual
-- implementation is done at the application level in:
-- 1. src/app/login/page.tsx - Checks suspension status after login
-- 2. src/components/providers/SupabaseProvider.tsx - Auto signs out suspended users
--
-- This is because we cannot modify the auth schema directly.
-- The application-level checks ensure suspended users:
-- - Cannot log in (login page check)
-- - Are automatically signed out if they have an active session (provider check)
-- =====================================================

-- This file is kept for documentation purposes but contains no executable code
