-- Create listing_pack_items table to store individual stickers in a group/pack listing
CREATE TABLE IF NOT EXISTS public.listing_pack_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id bigint NOT NULL REFERENCES public.trade_listings(id) ON DELETE CASCADE,
  template_id bigint REFERENCES public.collection_templates(id) ON DELETE SET NULL,
  slot_number integer,
  slot_variant text,
  page_title text,
  label text,
  created_at timestamp with time zone DEFAULT now()
);

-- Enable RLS on the table
ALTER TABLE public.listing_pack_items ENABLE ROW LEVEL SECURITY;

-- Create placeholder policies to be updated by 20260601093700
CREATE POLICY "listing_pack_items_delete" ON public.listing_pack_items
  FOR DELETE TO authenticated
  USING (true);

CREATE POLICY "listing_pack_items_insert" ON public.listing_pack_items
  FOR INSERT TO authenticated
  WITH CHECK (true);

CREATE POLICY "Anyone can read pack items" ON public.listing_pack_items
  FOR SELECT
  USING (true);
