-- Migration: Remove automated chat moderation reports for abusive language
-- Created: 2026-08-25
-- Description: Drops the automated chat moderation trigger and function that scanned trade chat messages
-- for abusive language, threats, slurs, and sexual terms.
-- Manual reports between users (via Report buttons/modals and create_report RPC) remain fully active.
-- Automated reports and blocking for URLs (auto_report_listing_url and block_urls_in_chat_message) remain fully active.

-- 1. Drop the automated chat moderation trigger on trade_chats
DROP TRIGGER IF EXISTS trigger_auto_moderate_chat ON public.trade_chats;

-- 2. Drop the trigger function
DROP FUNCTION IF EXISTS public.auto_moderate_chat_message();

-- 3. Auto-dismiss any remaining pending reports that were generated by the automated chat moderation
UPDATE public.reports
SET status = 'dismissed',
    admin_notes = 'Auto-dismissed: Deprecated automated chat moderation false positive'
WHERE reporter_id = 'b644414f-73d8-4dc3-a36c-964a933e4eb8'
  AND status = 'pending';
